import { CheckCircle2, Circle, Phone, Mail, Calendar, ClipboardList, Plus } from "lucide-react";
import { PageHero, SectionHeader, Badge } from "../components/ui.jsx";
import { ACTIVITIES } from "../data/mockData.js";

const WEEK = ["Mon", "Tue", "Wed", "Thu", "Fri"];

const SAMPLE_WEEK = {
  Mon: [
    { time: "09:30", title: "Discovery · Aegean Threads", type: "call" },
    { time: "14:00", title: "Send Smart Checkout proposal · Urban Beans", type: "email" }
  ],
  Tue: [
    { time: "11:00", title: "Demo · Ionian Resorts", type: "demo" },
    { time: "16:30", title: "Renewal check-in · Helios Apparel", type: "call" }
  ],
  Wed: [{ time: "10:00", title: "MCA offer follow-up · Marina Bistro", type: "follow" }],
  Thu: [
    { time: "09:00", title: "Weekly QBR with Elena", type: "task" },
    { time: "15:00", title: "Negotiation · Nova Mobility", type: "call" }
  ],
  Fri: [{ time: "11:30", title: "Onboarding kick-off · Olive & Vine", type: "demo" }]
};

const ICON = { call: Phone, email: Mail, demo: Calendar, follow: Mail, task: ClipboardList };
const COLOR = { call: "sky", email: "indigo", demo: "viva", follow: "amber", task: "slate" };

export default function ActivityPlanner() {
  return (
    <div>
      <PageHero
        title="Activity Planner"
        subtitle="Plan your sales week — calls, emails, demos and follow-ups — with suggested next-best actions per merchant."
        right={<button className="btn btn-primary"><Plus size={14} /> New Activity</button>}
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
        {[
          { k: 12, v: "Due today" },
          { k: 34, v: "Scheduled this week" },
          { k: 8, v: "Overdue" }
        ].map((s) => (
          <div key={s.v} className="card p-5">
            <div className="text-xs uppercase tracking-wider text-slate-500">{s.v}</div>
            <div className="mt-1 text-3xl font-bold text-viva-300">{s.k}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-5 gap-4">
        {WEEK.map((day, i) => (
          <div key={day} className="card p-4">
            <div className="flex items-center justify-between mb-3">
              <div>
                <div className="text-xs uppercase tracking-wider text-slate-500">{day}</div>
                <div className="text-lg font-bold">{13 + i} Apr</div>
              </div>
              {i === 0 && <Badge color="viva">Today</Badge>}
            </div>
            <div className="space-y-2">
              {SAMPLE_WEEK[day].map((e, k) => {
                const Icon = ICON[e.type] || ClipboardList;
                return (
                  <div key={k} className="rounded-xl border border-white/5 p-3 hover:border-viva-500/30 transition">
                    <div className="flex items-center gap-2 text-xs text-slate-400">
                      <Icon size={12} /> {e.time}
                    </div>
                    <div className="mt-1 text-sm font-medium text-slate-100">{e.title}</div>
                    <div className="mt-1">
                      <Badge color={COLOR[e.type]}>{e.type}</Badge>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>

      <div className="card p-5 mt-6">
        <SectionHeader title="Today's tasks" subtitle="Focus list generated by AI from your deals" />
        <ul className="space-y-2">
          {ACTIVITIES.slice(0, 5).map((a) => (
            <li key={a.id} className="flex items-start gap-3 p-3 rounded-xl border border-white/5 hover:border-viva-500/30 transition">
              <span className="mt-0.5">
                {a.status === "done" ? (
                  <CheckCircle2 size={18} className="text-viva-400" />
                ) : (
                  <Circle size={18} className="text-slate-500" />
                )}
              </span>
              <div className="flex-1">
                <div className="text-sm font-medium text-slate-100">{a.title}</div>
                <div className="text-xs text-slate-400 mt-0.5">{a.company} · {a.dueIn}</div>
              </div>
              <button className="btn btn-soft text-xs">Complete</button>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
